### ISSUE TITLE
[切版] 消費者訂位頁面

### ISSUE THREAD

**Issue by YorkYeh** [astrocamp/14th-iDing#11]
![image](https://github.com/astrocamp/14th-iDing/assets/138083856/988095f4-8d98-4876-8806-28ec50c541d5)
![image](https://github.com/astrocamp/14th-iDing/assets/138083856/be72d54d-4f80-473e-bce2-15003773acbd)

點擊訂位後的頁面
表單內包括
名字、電話、email、目的、備註 
(人數時間不用，在上個餐廳介紹頁面時就有包含了)
捲動時左側圖片會隨著滾輪移動

**Comment by tysaiw** [comment]
消費者端都要有 PC + moble
