### ISSUE TITLE
［修正］合作餐廳列表從大變小再從小變大按鈕會維持小的

### ISSUE THREAD

**Issue by tysaiw** [astrocamp/14th-iDing#146]
RWD的問題，縮小後文字會變 icon 但變大後按鈕還是 icon

**Comment by YorkYeh** [comment]
請問這個在說哪裡 我看蠻正常的?!
還是哪裡要調整?

https://github.com/astrocamp/14th-iDing/assets/138083856/ea732e01-e095-46f2-b233-2c8d82ebd56f

**Comment by tysaiw** [comment]
我從小變大的那個編輯按鈕會只剩下 icon 沒有字
https://youtu.be/har5-arKYmw
