### ISSUE TITLE
思考 Model 關聯 

### ISSUE THREAD

**Issue by YorkYeh** [astrocamp/14th-iDing#8]

**Comment by Kkrystalll** [comment]
昨天 Model 關聯 有想一些，的記得應該還有像是其他的 Model 例如 Table
可以先開始做後面再串關聯

**Comment by tysaiw** [comment]
整理的檔案在這邊：
https://docs.google.com/spreadsheets/d/131f5WbAXH8iqk1hFSZ-JC5wWHxGKL8HsF2IInXiMvro/edit#gid=0
